zuul:
  routes:
    ui:
      url: http://localhost:8081
    resource:
      url: http://localhost:9000
security:
  user:
    password: password
  sessions: ALWAYS
spring:
  devtools:
    livereload:
      enabled: false
logging:
  level:
    org.springframework.security: DEBUG